# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14c993a2a93eb5836bf7b39ecf7448d7da4a60e7104606508ae113ef6f9c9b316180d4ba16b1692d8f1454e8bae5caf0c2a631e337d452828bafc73acb053b29

test:
  secret_key_base: 9f05a7da2d5c89dc2ad926314c735a3608a5542541e7de04fa4420ab19250a8d20a4cb50e42742a9e6296bfb11a1ad6c2c32053ae0573eb69681bf5576cb1db1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
